name: CI
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          persist-credentials: "false"
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "latest"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ">=1.17.7"
      - name: Install pnpm dependencies
        run: pnpm install
        env:
          PUPPETEER_SKIP_DOWNLOAD: "true"
      - name: Qunit tests
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: "true"
        with:
          args: npm test
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            qunit-results.png
          retention-days: 1
      - name: Build chrome extension artifacts
        run: pnpm run build
        env:
          SIMKL_CLIENT_ID: ${{ secrets.SIMKLCLIENTID }}
          SIMKL_CLIENT_SECRET: ${{ secrets.SIMKLCLIENTSECRET }}
